data_params:
  data_path: '../datasets/'
  lagged_data_path: '../datasets/lagged/'
  save_path: '../results/'
  dataset: 'Segbana_with_SPI6.csv'
  city: 'Segbana'
  target_column: 'SPI6(t)'
  scaling_type: 'minmax'  # or 'standard' or 'none' or 'minmax'
  # feature_range: (-1, 1) # if scaling_type is 'minmax'
  include_target_lags: True
  split_date: '2014-01-31'
  window_size: 5
  n_output_steps: 1
  B_ARG: 30

conv1d_model:
  dense_layers: 3
  activ: ['relu', 'relu', 'linear']
  dense_units: [32, 8, 1]
  cnn_units: 64
  epochs: 200
  batch_size: 64

lstm_model:
  lstm_layers: 2
  dense_layers: 2
  activ: ['relu', 'linear']
  dense_units: [32, 1]
  lstm_units: [64, 32]
  dropout: False
  dropout_val: 0
  epochs: 500
  batch_size: 64

gru_model:
  gru_layers: 2
  dense_layers: 2
  activ: ['relu', 'linear']
  dense_units: [32, 1]
  gru_units: [64, 32]
  dropout: False
  dropout_val: 0
  epochs: 400
  batch_size: 64

conv1d_lstm_model:
  filters: 32
  kernel_size: 3
  lstm_layers: 2
  dense_layers: 2
  activ: ['relu', 'linear']
  dense_units: [32, 1]
  lstm_units: [64, 32]
  dropout: False
  dropout_val: 0
  epochs: 300
  batch_size: 64
